ITEM.Name = ".357 Ammo";
ITEM.Class = "weapon_357_ammo_shipment";
ITEM.ContentClass = "ammo_357"
ITEM.ContentCount = 10
ITEM.ContentItemWeight = 0.16
ITEM.Description = "10 pack";
ITEM.Model = "models/items/item_item_crate.mdl";
ITEM.Purchaseable = true;
ITEM.Price = 500;
ITEM.ItemGroup = 3;
