ITEM.Name = "Launched-Grenade Ammo (M9k)"
ITEM.Class = "weapon_40mmgrenade_ammo_m9k_shipment"
ITEM.ContentClass = "ammo_40mmgrenade_m9k"
ITEM.ContentCount = 10
ITEM.ContentItemWeight = 0.2
ITEM.Description = "10 pack"
ITEM.Model = "models/items/item_item_crate.mdl"
ITEM.Purchaseable = true
ITEM.Price = 1350
ITEM.ItemGroup = 5
