ITEM.Name = "AR2 Ammo"
ITEM.Class = "weapon_ar2_ammo_shipment"
ITEM.ContentClass = "ammo_ar2"
ITEM.ContentCount = 10
ITEM.ContentItemWeight = 0.18
ITEM.Description = "10 pack"
ITEM.Model = "models/items/item_item_crate.mdl"
ITEM.Purchaseable = true
ITEM.Price = 480
ITEM.ItemGroup = 3
