ITEM.Name = "Buckshot Ammo (M9K)";
ITEM.Class = "weapon_buckshot_ammo_m9k_shipment";
ITEM.ContentClass = "m9k_ammo_buckshot"
ITEM.ContentCount = 10
ITEM.ContentItemWeight = 0.25
ITEM.Description = "10 pack";
ITEM.Model = "models/items/item_item_crate.mdl";
ITEM.Purchaseable = true;
ITEM.Price = 592;
ITEM.ItemGroup = 3;
