ITEM.Name = "Buckshot Ammo"
ITEM.Class = "weapon_buckshot_ammo_shipment"
ITEM.ContentClass = "ammo_buckshot"
ITEM.ContentCount = 10
ITEM.ContentItemWeight = 0.25
ITEM.Description = "10 pack"
ITEM.Model = "models/items/item_item_crate.mdl"
ITEM.Purchaseable = true
ITEM.Price = 780
ITEM.ItemGroup = 3
