ITEM.Name = "Buggy"
ITEM.Class = "buggy_car"
ITEM.Description = "Basic vehicle"
ITEM.Model = "models/buggy.mdl"
ITEM.VehicleScript = "scripts/vehicles/jeep_test.txt"
ITEM.VehicleClass = "prop_vehicle_jeep"
ITEM.VehicleExtras = nil -- Bodygroup options go here.
ITEM.Purchaseable = true -- Available to buy
ITEM.Price = 2500
ITEM.ItemGroup = 4 -- Appears in the business menu of the car dealer group
