ITEM.Name = "Pistol Ammo"
ITEM.Class = "weapon_pistol_ammo_shipment"
ITEM.ContentClass = "ammo_pistol"
ITEM.ContentCount = 10
ITEM.ContentItemWeight = 0.30
ITEM.Description = "10 pack"
ITEM.Model = "models/items/item_item_crate.mdl"
ITEM.Purchaseable = true
ITEM.Price = 185
ITEM.ItemGroup = 3
