ITEM.Name = "Shotgun Ammo Shipment";
ITEM.Class = "weapon_shotgun_ammo_shipment";
ITEM.ContentClass = "ammo_shotgun"
ITEM.ContentCount = 10
ITEM.ContentItemWeight = 0.45
ITEM.Description = "10 pack";
ITEM.Model = "models/items/item_item_crate.mdl";
ITEM.Purchaseable = true;
ITEM.Price = 350;
ITEM.ItemGroup = 3;
