ITEM.Name = "SMG Ammo"
ITEM.Class = "weapon_smg_ammo_shipment"
ITEM.ContentClass = "ammo_smg"
ITEM.ContentCount = 10
ITEM.ContentItemWeight = 0.32
ITEM.Description = "10 pack"
ITEM.Model = "models/items/item_item_crate.mdl"
ITEM.Purchaseable = true
ITEM.Price = 730
ITEM.ItemGroup = 3
