ITEM.Name = "Flashbang Shipment";
ITEM.Class = "weapon_flashbang_shipment";
ITEM.ContentClass = "weapon_flash"
ITEM.ContentModel = "models/weapons/w_eq_flashbang.mdl";
ITEM.ContentCount = 10;
ITEM.ContentItemWeight = 3.8;
ITEM.Description = "10 pack";
ITEM.Model = "models/items/item_item_crate.mdl";
ITEM.Purchaseable = true;
ITEM.Price = 2340;
ITEM.ItemGroup = 3;
