ITEM.Name = "MP5 Shipment";
ITEM.Class = "weapon_mp5a5_shipment";
ITEM.ContentClass = "weapon_mp5a5"
ITEM.ContentCount = 10
ITEM.ContentItemWeight = 3.8
ITEM.Description = "10 pack";
ITEM.Model = "models/Items/item_item_crate.mdl";
ITEM.Purchaseable = true;
ITEM.Price = 2850;
ITEM.ItemGroup = 3;