ITEM.Name = "Scout Shipment";
ITEM.Class = "weapon_scout_shipment";
ITEM.ContentClass = "weapon_scout"
ITEM.ContentCount = 10
ITEM.ContentItemWeight = 3.6
ITEM.Description = "10 pack";
ITEM.Model = "models/Items/item_item_crate.mdl";
ITEM.Purchaseable = true;
ITEM.Price = 4750;
ITEM.ItemGroup = 3;