ITEM.Name = "C4 (M9K)"
ITEM.Class = "weapon_c4_m9k_shipment"
ITEM.ContentClass = "bb_planted_alt_c4"
ITEM.ContentModel = "models/weapons/2_c4_planted.mdl"
ITEM.ContentCount = 10
ITEM.ContentItemWeight = 4
ITEM.Description = "10 pack"
ITEM.Model = "models/items/item_item_crate.mdl"
ITEM.Purchaseable = true
ITEM.Price = 5880
ITEM.ItemGroup = 5
