ITEM.Name = "M4A1 Shipment";
ITEM.Class = "weapon_m4a1_shipment";
ITEM.ContentClass = "weapon_m4a1"
ITEM.ContentCount = 10
ITEM.ContentItemWeight = 3.9
ITEM.Description = "10 pack";
ITEM.Model = "models/Items/item_item_crate.mdl";
ITEM.Purchaseable = true;
ITEM.Price = 2550;
ITEM.ItemGroup = 3;