ITEM.Name = "Galil Shipment";
ITEM.Class = "weapon_galil_shipment";
ITEM.ContentClass = "weapon_galil"
ITEM.ContentCount = 10
ITEM.ContentItemWeight = 3.85
ITEM.Description = "10 pack";
ITEM.Model = "models/Items/item_item_crate.mdl";
ITEM.Purchaseable = true;
ITEM.Price = 3650;
ITEM.ItemGroup = 3;