ITEM.Name = "Five-Seven Shipment";
ITEM.Class = "weapon_five_seven_shipment";
ITEM.ContentClass = "weapon_five_seven"
ITEM.ContentModel = "models/weapons/w_pist_fiveseven.mdl";
ITEM.ContentCount = 10;
ITEM.ContentItemWeight = 1.8;
ITEM.Description = "10 pack";
ITEM.Model = "models/Items/item_item_crate.mdl";
ITEM.Purchaseable = true;
ITEM.Price = 970;
ITEM.ItemGroup = 3;
