ITEM.Name = "Grenade Shipment";
ITEM.Class = "weapon_grenade_shipment";
ITEM.ContentClass = "weapon_grenade"
ITEM.ContentCount = 10
ITEM.ContentItemWeight = 0.3
ITEM.Description = "10 pack";
ITEM.Model = "models/Items/item_item_crate.mdl";
ITEM.Purchaseable = true;
ITEM.Price = 2300;
ITEM.ItemGroup = 3;