ITEM.Name = "Winchester Ammo (M9K)"
ITEM.Class = "weapon_winchester_ammo_m9k_shipment"
ITEM.ContentClass = "m9k_ammo_winchester"
ITEM.ContentCount = 10
ITEM.ContentItemWeight = 0.24
ITEM.Description = "10 pack"
ITEM.Model = "models/items/item_item_crate.mdl"
ITEM.Purchaseable = true
ITEM.Price = 795
ITEM.ItemGroup = 3
